### ISSUE TITLE
Feature - Allow user to populate labels/collections based on file path filter

### ISSUE THREAD

**Issue by ChrisWeiss** [Floppy/van_dam#1038]
It'd be awesome if you could allow users to enter a filter string allowing them to automatically assign tags and collections based on elements of the file name/path. A good example is something like MediaMonkey, an audio file manager - here's their help for that function https://www.mediamonkey.com/wiki/Auto-Tag_from_Filename

**Comment by Floppy** [comment]
We've done it! This is in the v0.42.0 release that we just pushed out. Take a look, see what you think :)
