### ISSUE TITLE
Organize files from bulk_edit raising destination_exists problem

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#1059]
it seems like a bulk_edit move_files is acting differently than from the organize files in a model, and even though it is performing the move, it is raising a destination_exists.

The only way that this seems likely that it could happen is that somehow move_files is being called twice?

**Comment by Floppy** [comment]
That's odd! Does it depend on whether or not the model ID suffix is turned on in your settings? Because the ID is there to avoid any naming conflicts, if it's off, conflicts are possible, which wasn't a thing before. I've been meaning to check that gets handled OK (which it probably doesn't)

**Comment by ksuquix** [comment]
I'll have to play around a bit with it... I just noticed a few hundred problems after doing a large bulk edit, even though all of them successfully moved.

**Comment by Floppy** [comment]
Just realised this is probably the same thing as I've logged in #1089. In that case I've still got `{modelId}` in there, so that's not it.

**Comment by ksuquix** [comment]
Yes, definitely #1089 is a duplicate.   Even if you have {modelId} that's not a safeguard for someone doing something manual in the filesystem, so the check is still necessary IMO.   I'm still convinced the rename is getting triggered twice and failing the second time because it already happened.  I'll try to look at this issue next, because it's certainly a bit annoying.
