### ISSUE TITLE
destination_exists not automatically cleaned up

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#1060]
It seems like destination exists could potentially get automatically cleaned up if an object is successfully renamed and moved to a new location.

I'm not terribly sure the check works right and prevents everything from getting into a strange state either... This just needs to be fleshed out more and fully tested.

**Comment by ksuquix** [comment]
The check is indeed effective, so no worries there.   Wouldn't be bad to automatically clean up problems if they are no longer relevant though.

**Comment by Floppy** [comment]
I should add this to the problem cleanup during model scan.

**Comment by Floppy** [comment]
I'm thinking that destination_exists should be a validation error on model save, not a Problem created in the list. Those are more for inconsistencies in the way the library is organised, rather than actual validation errors. If that makes sense.
