### ISSUE TITLE
Some models duplicated on rescan

### ISSUE THREAD

**Issue by Floppy** [Floppy/van_dam#1093]
Not quite sure how to even describe this, but something's off. Putting this here as a vague placeholder until I can nail it down. Something to do with "organize", then "scan".

**Comment by Floppy** [comment]
Could be related to #1086 and #1089

**Comment by ksuquix** [comment]
Very likely #1086 .

**Comment by Floppy** [comment]
I've worked out what this is, I think; it's because organize was creating paths without leading separators, and library scan was creating them WITH, so you end up with two copies of the same model after organise, one without slash and one with. I've written a fix which will removes separators at the start and end of model paths, both for new models and as a data migration for existing ones. If there is a double-model in the database, the one that had separators will be destroyed, as that's likely to be the new duplicated one.
