### ISSUE TITLE
Add preview model choice in collection

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#1114]
Floppy: This is probably a "next PR" type thing, but being able to choose the preview model (in the same way you can choose a preview file for a model) would be awesome.

ksuquix: Going a step further, being able to do the choice and/or set it's own image completely might be good (same with creator).

**Comment by Floppy** [comment]
duplicate of #1105?

**Comment by Floppy** [comment]
this one has more, I'll close the other.

**Comment by Floppy** [comment]
Duplicated by #5381, so I'll close this one, but the work continues over there :)
