### ISSUE TITLE
Library menu doesn't collapse

### ISSUE THREAD

**Issue by mcsgroi** [Floppy/van_dam#1120]
Hello @Floppy ,

I just noticed that if you create too many libraries, the top menu bar overflows and the styling more or less breaks. Have you considered any options for collapsing that bar if it becomes too large relative to screen size?

![image](https://user-images.githubusercontent.com/8921172/226036311-0eb47933-6fbb-40df-b312-b0e778763473.png)

**Comment by Floppy** [comment]
Yeah, as the thing fills up with more buttons I definitely need to revisit the navbar flow! Thanks for pointing it out :)

**Comment by ksuquix** [comment]
As a workaround until this gets changed, you can now cosmetically shorten the names of the libraries you have and choose specific icons in settings.   That's what I've done to my setup.
