### ISSUE TITLE
Creators with no models don't appear in listing. Duplicate Creators allowed.

### ISSUE THREAD

**Issue by mmontminy** [Floppy/van_dam#1301]
Version v0.44.0 (8514c144)
I created a new Creator with just a name from the Creators section and it didn't appear. Thinking I might have forgotten to hit Save I did it again and it still didn't appear.
Then I did a scan to pick up the model from that creator and the creator appeared.
Advanced admin showed 2 creators, and I was easily able to delete the hidden duplicate.
I don't recall previous versions doing this as this was my normal workflow before picking up the creator from the folder name was an option.

**Comment by Floppy** [comment]
Thanks for filing this - there's a bit of strange behaviour in the model lists, and some of the filtering is spilling over into other lists like collections and creators, which is causing this I think. I'll have a dig in.

**Comment by Floppy** [comment]
In the case where you had a duplicate, was the name identical, or did it differ in case or hyphenation?

**Comment by Floppy** [comment]
v0.45.0 definitely fixes some of the issues where duplicate creators can be created by the path scanner, it's worth upgrading to that to improve things a bit.

**Comment by mmontminy** [comment]
The name was identical, and manually entered. Simple one-word, no punctuation, basic title case name. I wasn't aware until recently that the path scanner would create a creator, so my workflow was to manually enter it, then scan.

I manually entered it, went to edit it to add a URL and couldn't find it. Figuring I just forgot to click save, I created it again and it still didn't appear. Once I scanned and a model was linked, then it appeared.

I did just upgrade to 0.45.0, but haven't tried to see if it's still an issue.

**Comment by Floppy** [comment]
Thanks, I'll take a look into it.

**Comment by mmontminy** [comment]
Empty creators now appear, and duplicates are given a unique ID after the upgrade.
Note, it did prefer the newest creator and appended an id to the original. Not a big deal to go through and delete the duplicate and rename the original, but it would be nicer if it selected the oldest creator and renamed the newer.

A possible side-bug from this is that it's no longer auto-filling the creator when scanning.

Even when the folder name is an exact match for the creator, it doesn't appear to pick up the creator and you need to manually select it while editing the model.

**Comment by Floppy** [comment]
Thanks @mmontminy. I didn't really specify which model should be renamed, keeping the oldest unchanged is a good idea.

I'll have a look at how it's auto-filling the creator... it might *just* be doing it based on slug now, rather than name OR slug. I'll check.
