### ISSUE TITLE
New install asking for email login or sign up

### ISSUE THREAD

**Issue by MartytheMonster** [Floppy/van_dam#1328]
Just set this up on an unraid server. Everything looks like it is running but when I go to the page at http://192.168.1.109:3214/admin/login
it says I need to sign in or register.

Have tried both using the docker image and the example compose file using the compose app addon in uraid. If anyone can tell me where I have gone wrong that would be awesome. 

Thanks.

**Comment by Floppy** [comment]
Oh, that's weird, it should automatically set up an admin user and sign you in; multiuser isn't really a thing yet. I'll run a fresh copy up locally and see if the same thing happens!

**Comment by andypiper** [comment]
It didn't do that for me - I have had to set up a user via the Rails console.

**Comment by Floppy** [comment]
Thanks - looks like that autogeneration of the admin user has broken. Which version are you using?

**Comment by bacardiman04** [comment]
I am getting the same
v0.47.1

**Comment by andypiper** [comment]
Version v0.47.1 (677067c2) - which is basically git HEAD I think, as I installed from a git clone rather than taking a versioned release. I did have a dig around in the source yesterday looking to see how the Devise stuff was trying to set up that user, but gave up and created my own.

**Comment by MartytheMonster** [comment]
Just tried 0.46.0 and that seems to be working. Be aware however I have no idea what I am doing

**Comment by Floppy** [comment]
No, that makes sense @MartytheMonster, I've worked out that a change I made in v0.47.0 meant that that user didn't get created. I'm releasing a fix soon.

**Comment by Floppy** [comment]
v0.48.0 is building now and includes a fix, so if you upgrade in a couple of hours' time, it should fix itself.
