### ISSUE TITLE
QOL tweaks

### ISSUE THREAD

**Issue by slitzer** [Floppy/van_dam#1361]
I have been long waiting for this, the abillity to easily view my 3d files faster than explorer!

A couple ideas to thow onto the pile , based on my usage

- as mentioned here somewhere, abliliy to click into an image (or gif, love this btw) to open 
- Dark Theme
- Image/Cover resize/scaled to view the whole image, I have a bit of artwork that is not 1:1 ratio (maybe an option for scaled to fit, 1:1, stretched
- User management, even just a user/admin type role with no option to delete
-  Favorites on the main item page for quick likes
- Mobile web works on phone great, just the libray's take up the whole screen before seeing a model

Not sure how much work that is, a bit i'd imagine - anyways keep up the great work

Kind Regards

**Comment by Floppy** [comment]
That fantastic feedback. Could I be a complete pain and ask you to make each one into a separate issue, so I can add them to the list easily, prioritise, and push them out one by one? There are a couple (users, click on image) that are already there, so add a +1 on those maybe?

**Comment by slitzer** [comment]
sure thing, will do, might need to be later today 👍

**Comment by Floppy** [comment]
No rush, I'm off on holiday for a week anyway :)

**Comment by slitzer** [comment]
Done, created seperate issues :)
