### ISSUE TITLE
QOL - Tweak 01 - Main Image Cover Resize

### ISSUE THREAD

**Issue by slitzer** [Floppy/van_dam#1364]
Would be good to have the ability to scale an image that is not 1:1 

I have a bit of artwork that is not 1:1 ratio (maybe an option for scaled to fit, 1:1, stretched

Also not sure how easy this would be, but perhaps a way to grab a screenshot of current 3D model to use as cover art.
I found having an image rather then the model speeds up the site quite a bit

Another thought for future tuning - maybe an option to cycle thorugh images in the root folder, Im thinking like 4 or so images of a model from differant angles could be quite cool to cycle thorugh them - although this could look a little myspacey XD

**Comment by Floppy** [comment]
I've done a bit of a tweak to the cover images in #1399, though I don't know if this resolves the problem you're seeing?

**Comment by Floppy** [comment]
I think this is sorted.
