### ISSUE TITLE
QOL - Tweak 02 - Dark theme

### ISSUE THREAD

**Issue by slitzer** [Floppy/van_dam#1365]
A minor niggle as I understand this is a cosmetic change rather then funtional but a dark theme of sorts?

**Comment by Floppy** [comment]
Looks like https://caniuse.com/prefers-color-scheme is very well supported, so this is doable. I bet there's a default bootstrap theme that has dark mode auto-selection, too.

**Comment by Floppy** [comment]
Aha, bootstrap has a dark mode option in 5.3: https://getbootstrap.com/docs/5.3/customize/color-modes/#building-with-sass
