### ISSUE TITLE
Nested Folders

### ISSUE THREAD

**Issue by lloydpick** [Floppy/van_dam#1378]
Hi,

I mainly use van dam for keeping copies of STLs from various websites, rather than for models I created myself. As such I'd like to have a Library per site, and within that have the capability of deep nesting with folders, for example...

fab365/saturnv/firststage/bottom_white.stl
fab365/saturnv/firststage/middle_white.stl
fab365/saturnv/secondstage/bottom_white.stl
fab365/foldable-walle/arm.stl
fab365/foldable-walle/hand.stl
etc

As some of the models get quite large in terms of sections or number of stls, it helps to be able to use deeper folders to manage them. It appears at the moment I'm limited to a single directory within a library? I might have done this wrong, but it didnt appear to work the way I wanted.

**Comment by Floppy** [comment]
You certainly can do that - I have a very large library containing many folders. Any folder that contains scannable files should be treated as a separate model, so in your case you should be getting `secondstage`, `firststage` and `foldable-walle` models. If you also have anything scannable in `saturnv` (like a preview image), then it will show up nested models for the others within it, which you can either leave separate or merge.

What do you get? Is `fab365` your ilbrary folder? What models do you get?

You're right on large complex models with merged subfolders, they're currently difficult to navigate, and it's something I want to improve in #50.

**Comment by Floppy** [comment]
This is very similar to #1368 too, perhaps that might help.

**Comment by lloydpick** [comment]
Ah, ok I got it figured out now, I didn't realize that I needed something like a screenshot in the top level directory to group up all the models together. This seems to work fine. The only issue seems to be that its shortening directory names, for example "First Stage Assembly" just ends up as "First" etc.

**Comment by Floppy** [comment]
Ah, yes, that would do it. I do want to allow merging of models that don't have a common parent at some point, which would avoid the need for anything in the top directory. 

I think the shortened directory name thing (assuming you mean within a model, not the model name) is because of way it tries to group parts together, but doesn't really understand subdirectories. That's due a rewrite in #50 as well.
