### ISSUE TITLE
Errors in admin interface due to Ransack

### ISSUE THREAD

**Issue by Floppy** [Floppy/van_dam#1402]
Upgrading to ActiveAdmin 3.0 also included Ransack 4.0, which now requires you to specify searchable fields, as a security measure. This is done for our own models in #1400, but I'm now coming up against problems enabling it for DelayedJob tasks and [ActsAsTaggableOn](https://github.com/activerecord-hackery/ransack/discussions/1416) tags. 

Currently the tags, tasks, and model lists throw ransack errors (I assume Model is because of tags being broken, currently).

**Comment by slitzer** [comment]
Is this the related to when ever I select any of the admin tabs at the top I get this error
![image](https://github.com/Floppy/van_dam/assets/12588795/9326d981-1092-4a6a-9e19-2a290cf13eba)

The only page that loads is the Dashboard

**Comment by Floppy** [comment]
Yes, that's why. I have a partial fix for this already, I'll push out a release soon.

**Comment by slitzer** [comment]
Perfect, thanks so much, all working now - and LOVE the artwork scalling - nice job

**Comment by Floppy** [comment]
Thanks! The models, tasks, and tags views in admin are still broken, but progress is progress :)
