### ISSUE TITLE
Can’t Upload Files

### ISSUE THREAD

**Issue by MrGreen01010** [Floppy/van_dam#1420]
Tried uploading an stl file but, does not upload. Redirects to something went wrong page.

**Comment by Floppy** [comment]
I'll check it out - it might be expecting a zip file, rather than an individual STL, that might be what's breaking it. 👍🏻

**Comment by MrGreen01010** [comment]
Yup, wanted a zip file. If working with a single file it just needs to be compressed and all is good.
