### ISSUE TITLE
Connection Issue to PostgreSQL on Synology 

### ISSUE THREAD

**Issue by neonnt** [Floppy/van_dam#1471]
hi there

i was trying to run vandam on Synology DSM 7.2 as a project on container manager with docker-compose.yml from the example with modified volumes path for libraries and password etc.

but there seems to a connection issue between vandam and the postgresql db. after about 2 minutes it gets you can see a connection timeout and vandam is stopped.

attached some logs. are there any suggestions to run it properly?

[vandam-app-1.csv](https://github.com/Floppy/van_dam/files/12506605/vandam-app-1.csv)
[vandam-db-1.csv](https://github.com/Floppy/van_dam/files/12506606/vandam-db-1.csv)
[vandam-redis-1.csv](https://github.com/Floppy/van_dam/files/12506607/vandam-redis-1.csv)

**Comment by Floppy** [comment]
Hm, could be the docker network config perhaps? Could you paste the configuration somehow?

Have you seen @andypiper's guide at https://andypiper.co.uk/2023/07/05/running-a-3d-print-catalogue-with-van-dam/? That might help identify any differences?

**Comment by neonnt** [comment]
Docker Network
Subnet: 172.23.0.0/16
Gateway: 172.23.0.1
IP Masquerade: network:enable

vandam: 172.23.0.4
postresql: 172.23.0.2
redis: 172.23.0.3

+++++++++++++++++++++++++

according to Andys guide i've changed volumes path for libraries to my shared folder and passwords
[docker-compose.txt](https://github.com/Floppy/van_dam/files/12515350/docker-compose.txt)

**Comment by neonnt** [comment]
hi
after messing around quite some time, vandam is finally running on my synology

i had to 
- create a docker network manually on synology container manager
- open firewall for this network (maybe it was the main issue for all of this connection problems)
- adjust some settings in docker compose.yml

`version: "3.6"
services:
  vd-app:
    image: ghcr.io/floppy/van_dam:latest
    networks:
      default:
        ipv4_address: 172.18.0.18
    ports:
      - 3214:3214
    volumes:
      - /volume1/3dprint/GCode_STL:/libraries
    environment:
      DATABASE_URL: postgresql://vandam:vandam@172.18.0.14/van_dam?pool=5
      SECRET_KEY_BASE: OnerWElANdiCkloWINCtIVEntONoTh
      REDIS_URL: redis://172.18.0.15:6379
    depends_on:
      - vd-db
      - vd-redis
    links:
      - vd-db
      - vd-redis

  vd-db:
    image: postgres:15
    volumes:
      - /volume1/docker/vandam/postgresql/db_data:/var/lib/postgresql/data
    networks:
      default:
        ipv4_address: 172.18.0.14
    environment:
      POSTGRES_DB: van_dam
      POSTGRES_USER: vandam
      POSTGRES_PASSWORD: vandam
    restart: on-failure

  vd-redis:
    image: redis
    volumes:
      - /volume1/docker/vandam/redis:/data
    networks:
      default:
        ipv4_address: 172.18.0.15
    restart: on-failure

networks:
  default:
    name: vandam
    external: true`

**Comment by Floppy** [comment]
That's great to hear, and thanks so much for posting the working configuration. I've linked this ticket to #1239 which should hopefully end up with some documentation being written on how to do this, so we can include your experience in that!
