### ISSUE TITLE
Add support for GCode files

### ISSUE THREAD

**Issue by ToasterUwU** [Floppy/van_dam#1533]
Specifically im thinking that I can upload a known good GCode file, select the printer its for, and then reuse it when I need to. That way I don't need to remember if I needed custom setting and which exactly. I figure it out once, and upload it.

Not high priority in my head, especially not with the PR existing that makes the files overview better and also shows all kinds of files, but if there is ever time for this, this would be pretty cool.

**Comment by Floppy** [comment]
That's a really good point. Why didn't I think to add that already? I can add file support easily, and the file notes could be used to say which printer it's for 👍🏻
