### ISSUE TITLE
Change to a more understandable name

### ISSUE THREAD

**Issue by Floppy** [Floppy/van_dam#1623]
Pun-based names are fine for starting out, but once other people start using a project, it makes sense to change to something more descriptive. It's probably that time for this project, but naming is hard. 

I want to find a name that includes ideas of 3d printing and graphics, as well as self-hosting, indendence, freedom, and perhaps federation and decentralisation.

Any suggestions greatly appreciated!

**Comment by davefp** [comment]
* Selfstruder
* MeshHost
* MyMeshManager (maybe too close to MyMiniFactory)
  * MultiMeshManager
* FabLib (lib for both libre and library)

Stopping now because **FabLib** is my favourite 😁

**Comment by loleg** [comment]
- Makersphere
- DoitDoitDone
- Open Printable

As per Mastodon. Have not yet researched, but happy to come up with more if you want! Congrats, awesome project. I kinda miss Poly, and hope this becomes the new hub and watercooler for 3D modelling communities.

**Comment by Jafner** [comment]
Some dryer options could be:

- OpenDAM
- LibreDAM
- FreeDAM

**Comment by Floppy** [comment]
Thank you everyone, these are all going on the list 😄

**Comment by Floppy** [comment]
After much brainstorming, I've settled on **Manyfold** as the new name (pronounced more like "manifold"). I'll be moving over as I work out the implications for docker packages etc. 🎉

**Comment by Jafner** [comment]
That's a great name! Rolls off the tongue and not conflicting with any other software projects.
