### ISSUE TITLE
Tag editing

### ISSUE THREAD

**Issue by Floppy** [Floppy/van_dam#28]
Add, remove, and create new tags manually.

**Comment by itisnot-me** [comment]
Though I know you are working on this as a milestone, this one feature is something a lot of people need to have. For those who buy and sell prints it would be best to be able to look up via special tags. For example if someone is looking for a half blood orc all they have to do is search the tag and all those files show up through different creators. 

This one thing would get a lot of people to download and use this

**Comment by Floppy** [comment]
Thanks! Good to know what people need first :)

**Comment by mattpage** [comment]
🎉 The ability to add/remove/edit tags is now a released feature 🎉
