### ISSUE TITLE
app container fails in docker

### ISSUE THREAD

**Issue by ZacharyJSmit** [Floppy/van_dam#446]
The app container fails in docker.  I'm using docker in portainer.  
The db and redis containers both spin up fine and wait for connections.

The log file from the app container

Preparing database...
bundler: command not found: rails
Install missing gem executables with `bundle install`

![2022-03-29 15_21_59-Portainer](https://user-images.githubusercontent.com/100300390/160691139-45d54e57-a460-4ad7-bfa0-e0504af4332d.png)

**Comment by Floppy** [comment]
Oh, that's weird. I'm using the docker container myself on my media server, so that's really odd.  Perhaps it's a portainer thing, or maybe it's a brand-new installation thing. Or maybe it's an architecture thing, maybe my x86 build is bad (I'm using arm on a raspberry pi). What architecture is it running on?

**Comment by ZacharyJSmit** [comment]
I'm running portainer in a Debian VM on Proxmox as a hypervisor.

**Comment by Floppy** [comment]
Do you know if that's on x86 or arm hardware? I know very little about proxmox I'm afraid, so I'm not sure if it even matters!

Also, can I ask - where did you find the software? I've never had anyone using it before I don't think, and suddenly there are a bunch of issues coming in (unsurprisingly!)

**Comment by ZacharyJSmit** [comment]
Van_dam was recommended as a cool solution on /r/selfhosted reddit
https://old.reddit.com/r/selfhosted/comments/tp8nva/whats_the_biggest_missing_piece_of_the_puzzle_in/i2asxru/?context=3

Also, youtuber DB Tech did a full video showing setup and use hosting through portainer.
https://www.youtube.com/watch?v=FWj7WNPjOCw

Proxmox and Debian are x86 (Proxmox hypervisor OS is built on Debian)
I'm not a docker expert, but I don't think the host should conflict with the container in docker, as far as dependencies go, but I'm not confident about that.  It's possible another container on my docker environment could be creating a unique issue for me.  I tested a few different setups, and I end up at the same error posted above for the app container regardless if I use docker compose, or create the containers separately.

**Comment by Floppy** [comment]
Thanks! So nice to see people discovering this thing :)

I'll run up the x86 container on a machine here, verify it works there, then we can see what else might be wrong.

**Comment by ZacharyJSmit** [comment]
Update: I created a new Debian VM with a new docker / portainer instance.  The same docker compose file that failed originally, worked correctly on the new machine.  The app container loads all the way and I can get to the web interface.  I'm not sure what makes it work on one and not the other.  I thought the host OS of docker didn't matter.  Both docker hosts are debian VMs on hosted by proxmox, but it's possible one has more updates or something installed I don't remember.  I'm guessing it's more likely the difference between portainer / docker instances, where something is conflicting on my original host.

**Comment by Floppy** [comment]
Thanks for the update! Very odd how anything could conflict, that's like the entire point of docker! Glad you have it working, at least. I'll close this for now, but if you spot anything that might explain the difference and that I could do anything about, feel free to reopen it?
