### ISSUE TITLE
Feature request: queue new files to prompt info adding

### ISSUE THREAD

**Issue by haudankaivajasi** [Floppy/van_dam#447]
Hi.
I was thinking it would be awesome if this software would create a queue of newly imported stl-files and then prompts a user to fill in possible information such as tags etc and perhaps would then move files to folders accordingly. This way it would be easy to import new files and keep the library tidy.

**Comment by Floppy** [comment]
Nice idea! Automatic folder organisation is something that's been on my list too.

Can I ask - where did you find the software? I've never had anyone using it before I don't think, and suddenly there are a bunch of issues coming in (unsurprisingly!)

**Comment by haudankaivajasi** [comment]
There was a [discussion in reddit](https://www.reddit.com/r/selfhosted/comments/tp8nva/comment/i2asxru/?utm_source=reddit&utm_medium=web2x&context=3) about what is missing in the self-hosting scene. A day later there was [a video](https://www.youtube.com/watch?v=FWj7WNPjOCw) about it.
