### ISSUE TITLE
Feature Request: Upload support 

### ISSUE THREAD

**Issue by freakadings** [Floppy/van_dam#450]
I was looking for a hosting solution to share stls for me and my friends of our local printing-group and just found this awesome peace of software and set it up immediately. It's realy great!

But i got a big request: Is it possible to add multi-user support (or one password protected account) with the possibility to upload files? I then could it make "public" to my friends and share the credentials. 

We would appreciate it very much!

Greetings and thank you so much for sharing your work!

**Comment by Floppy** [comment]
Nice idea! It doesn't currently have upload or file organisation support at all, so we'd need that first, but having multi user accounts to make a shared archive would be a great addition. I'll add it to the list!

**Comment by TheBinaryLoop** [comment]
I think file organisation/upload support is one of the most important features right now. It would make the program a whole lot more usable.

**Comment by Floppy** [comment]
This is because you're the absolute first person to try it! I've not even looked at it myself yet. But, that's a good prompt for me to do so. I'll take a look this weekend and try to push out a working release for you. Thank you for the excellent bug report, it'll help me get it working quick :+1:

**Comment by Floppy** [comment]
I've split off the multiuser aspect of this into #647, as that will come along first before we can usefully do uploading. 👍🏻

**Comment by Floppy** [comment]
We've had a PR opened for this in #1081 , so it might get in the next release!

**Comment by Floppy** [comment]
It's merged in, so it will go out in v0.43.0 !
