### ISSUE TITLE
Proposal - Make pagination the default

### ISSUE THREAD

**Issue by mattpage** [Floppy/van_dam#480]
On my mac, continuous scroll starts to lock up Chrome if I scroll through more than a couple dozen models.

Threejs also emits a lot of warnings like this:
```
three.module.js:20481 WARNING: Too many active WebGL contexts. Oldest context will be lost.
```

If we defaulted to pagination we could avoid this but still provide the option for continuous scroll to those that want it.
This seems to me like a more usable default setup, but what do you think @Floppy ?

**Comment by Floppy** [comment]
I think the active context thing is fixable with the thoughts in #449. But, I agree, on a large library, scrolling down to find something near the end is massively expensive for no real reason. Pagination will help, certainly, at least then you could jump to page 10 straight away and not load everything in between. You're probably right that pagination is a better default.
