### ISSUE TITLE
Add support for stp files

### ISSUE THREAD

**Issue by TheBinaryLoop** [Floppy/van_dam#551]

**Comment by Floppy** [comment]
This is a new one on me, so here's something for me to read: https://openstpfile.com/

**Comment by Floppy** [comment]
We'll need a STP loader for three.js, which should be doable. Other formats are here: https://github.com/mrdoob/three.js/tree/master/examples/js/loaders, we can hopefully build off one of those.

**Comment by beniroquai** [comment]
Hey @Floppy, was there any attempt to render the STEP files by any chance? stl files feel like the defacto standard for 3d printable objects, but STP is much nicer when it comes to additional editing :) 
I found this here, not sure if this can be applied (also license wise..): https://codesandbox.io/p/sandbox/view-step-file-with-three-js-5nfq9t?file=%2Fsrc%2FStepLoader.js
Thanks a lot for this great project!! :)

**Comment by beniroquai** [comment]
Thanks! I can try, but my Javascript skills are definitely limited. But: In best case it would be a `1+1=2` thing.. I'll have a look! :)
