### ISSUE TITLE
schema models out of sync

### ISSUE THREAD

**Issue by philstenning** [Floppy/van_dam#582]
When you pull/clone the repo and do the inital:

```
> bundle exec rake db:migrate:with_data
```

the schema.rb gets updated each time with this

![Screenshot 2022-07-03 102053](https://user-images.githubusercontent.com/1886110/177033634-a43c53cb-04fe-463b-9aaf-ffada81b05b1.png)

I just discard the changes, but wonder if something is out of sync somewhere?

**Comment by Floppy** [comment]
I noticed this yesterday... I think you're right, something's got out of sync. We can probably just remove those from the schema.rb, they were replaced with the `links` table, so they shouldn't be there.

**Comment by Floppy** [comment]
fixed in edb2fc5b4198ae15155c8d6762f9149c680ddc05
