### ISSUE TITLE
Scan leaves empty Models lying around

### ISSUE THREAD

**Issue by Floppy** [Floppy/van_dam#624]
If a models directory exists, but the files are missing on disk, but are still in the database (I think?), when the model is rescanned it will be left as an empty model. On a subsequent scan it will be cleaned up, but it should be removed first time.

**Comment by ksuquix** [comment]
So I just had a thing where I accidentally dropped an image file at the root of my tree and did a scan.   I removed the file then did a scan again, but there's a "model" that has nothing in it but a warning that it contains files from all my other models that I can't seem to get rid of... is this related?

**Comment by Floppy** [comment]
Oh, interesting, could be. It shouldn't index things in the root, but if you have a model that contains all the others, that looks like it has somehow.

That will help me replicate the problem, thanks!

If you scan again, the empty model should be removed.

**Comment by ksuquix** [comment]
It didn't remove it.  I read this issue and tried it already.

**Comment by Floppy** [comment]
This is no longer a problem, or rather it's intentionally the case. Models are no longer automatically removed if missing, because we could lose metadata. Instead we have "problems" which flag things like missing files to the user.

**Comment by Floppy** [comment]
@ksuquix you should find in the next release that this gets flagged up in the problem list, with a "purge" button to clean it up if you want to.
