### ISSUE TITLE
Unable to Start - looping

### ISSUE THREAD

**Issue by jsmith432** [Floppy/van_dam#629]
The container was working, but now it is in a loop.  I am not sure how there is already a server running? I am not able to get to the console. 

```
today at 3:13:03 PMContainer started
today at 3:13:04 PMPreparing database...
today at 3:13:05 PMMigrating data...
today at 3:13:07 PMLaunching application...
today at 3:13:07 PM15:13:07 rails.1  | started with pid 11
today at 3:13:07 PM15:13:07 worker.1 | started with pid 12
today at 3:13:08 PM15:13:08 rails.1  | => Booting Puma
today at 3:13:08 PM15:13:08 rails.1  | => Rails 7.0.3.1 application starting in production 
today at 3:13:08 PM15:13:08 rails.1  | => Run `bin/rails server --help` for more startup options
today at 3:13:08 PM15:13:08 rails.1  | A server is already running. Check /usr/src/app/tmp/pids/server.pid.
today at 3:13:08 PM15:13:08 rails.1  | Exiting
today at 3:13:08 PM15:13:08 rails.1  | exited with code 1
today at 3:13:08 PM15:13:08 system   | sending SIGTERM to all processes
today at 3:13:08 PM15:13:08 worker.1 | rake aborted!
today at 3:13:08 PM15:13:08 worker.1 | SignalException: SIGTERM
```

**Comment by Floppy** [comment]
Oh, that's an interesting one... I'll check it out

**Comment by Floppy** [comment]
which version are you running?

**Comment by jsmith432** [comment]
I am running version v0.27.0. I just ended up deleting the database and starting from scratch... I don't have many models, so that was easier than trying to troubleshoot why this happened.

**Comment by Floppy** [comment]
Ah, I was thinking you're using the docker container, but would I be right in saying you've built your own container for proxmox? It's possible, in that case, that if you built the container while you had a local app running as well, the pid file got included in the container by accident. That's a guess though, does it seem possible?

**Comment by jsmith432** [comment]
I did not build the container, I just use docker installed in an LXC. In fact, I used your docker-compose.example.yml with minimal changes. I only mounted libraries folder (per your example), and was surprised that somehow looks like this pid file was being persisted?
I deleted the database data and used the same docker-compose to just start new since it was working before.

**Comment by Floppy** [comment]
Hm, very odd then!

**Comment by ChronoStriker1** [comment]
I also have this issue, it seems to happen most when the docker is not shutdown gracefully (i.e. system crash or system shutting down before docker finishes shutting down its service)

**Comment by Floppy** [comment]
@ChronoStriker1 that makes sense. I will try to stop the pid file from persisting between docker sessions.
