### ISSUE TITLE
Feature: Notes field on a Model

### ISSUE THREAD

**Issue by lloydpick** [Floppy/van_dam#675]
It would be useful to have just a textarea on a model to store some notes. Like for example, I have a model of a fan shroud and I'd like to store a note along side with it saying "BL/3D Touch Offset: x-51 y-13". Otherwise I have to store this somewhere else. Could also store things like print settings, infill etc

**Comment by Floppy** [comment]
Nice idea! I'll pop it on the list. Do you think just Models, or for individual parts as well?

**Comment by lloydpick** [comment]
Probably both, the more places we can have notes the better really.

**Comment by tedbergstrand** [comment]
I just had this same thought. It would be nice to be able to have fields for Material, Infill %, and other comments (like if it takes a certain fastener, etc).

Being able to upload a README/How-To to complement model folders would handy for complex designs that still need to be built after printing.

**Comment by Floppy** [comment]
It's quite a straightforward change, Rails makes this really easy to add. Just needs a bit of time to get it done. PRs are welcome, of course!

**Comment by Netrecov** [comment]
Ah cool, So rails is the platform that is providing the back end for the website? I can research and see what i can do.

**Comment by ksuquix** [comment]
Funny coincidence, I started work on this issue yesterday :)
I expect I'll have a PR in the next day or two on it.  I'd probably have it done already, but I had to read up on how rails extends the database, etc.

**Comment by Floppy** [comment]
Haha @ksuquix I can't keep up!

**Comment by Netrecov** [comment]
thank you! will there be a new update, or do i need to reinstall the container?

**Comment by Floppy** [comment]
This will come out on v0.41.0, which I hope will get released later this week - just a couple of jobs left to do on it. Updating and restarting the container should be all you need to do.
