### ISSUE TITLE
Feature: Show all tags as clickable resources

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#763]
If you are in a model, you get the tags you can click on to see other related things, but this would be handy at either the top level or search page to list ALL tags, and also you can see inconsistencies (BoB vs. B.o.B. vs. bob, etc).

**Comment by Floppy** [comment]
The library currently shows all tags in that library - do you mean there should be another list with ALL tags, right up at the top level on the search page? I certainly think that's a useful idea, I've thought about it myself before...

**Comment by ksuquix** [comment]
Probably both.   However it doesn't seem like all tags are showing up at the library level.  

I think I didn't see it when I only had one test model in.... so maybe you are filtering out the tags that only exist in one model?

**Comment by Floppy** [comment]
Ah - yes. Tags that are only used once aren't shown, because they clutter the place up. Good spot. Whether that's a good design choice or not... 🤷🏻

**Comment by ksuquix** [comment]
#1063 and #963  eliminated every problem listed in this issue since you see all the libraries combined at the top model#index, and threshold is configurable now.
