### ISSUE TITLE
Library and config files should be 2 different binds

### ISSUE THREAD

**Issue by javijuji** [Floppy/van_dam#779]
The docker compose example recommends binding your library to 
 - /path/to/your/libraries:/libraries

We should be able to separate container files from our 3d model libraries such as:

- /volume1/docker/van_dam/config/:config
- /volume1/media/3dmodels/:libraries

**Comment by Floppy** [comment]
I don't *think* there's anything stored on disk for config, it's all in the database and environment variables? But I was thinking of changing the compose example to use sqlite, so that would need a separate place, certainly.
