### ISSUE TITLE
Search for missing tags/url/creator/etc

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#787]
It would be nice to do a search for things that don't have particular tags, or are missing creator/url/etc.

Then you can easily locate things that need updates.

**Comment by ksuquix** [comment]
Ah...   Need bulk editor on that unassigned  page too :)

**Comment by Floppy** [comment]
Some of this could be doable now with the `Problem` model; a missing creator for instance could be logged as a low-priority Problem, perhaps?

**Comment by ksuquix** [comment]
That assumes everyone uses the same structure....   I was thinking of extending the filter mechanisms for the models tree to be able to perform the function, and just have a button for each of the types of things (haven't gotten so far as to thinking about where to place those though).

**Comment by Floppy** [comment]
Yeah, on reflection, it's better just as a filter. Having a whole load of problems you can't get rid of would be irritating and noisy.

**Comment by Floppy** [comment]
Missing creator is now there in the unified search list; the rest of this should be possible now by extending the filtering.

**Comment by ksuquix** [comment]
#1053 takes care of collection/tags, url is still left to go.

**Comment by ksuquix** [comment]
last piece resolved by  #1064
