### ISSUE TITLE
Feature request: disable rotation of previews

### ISSUE THREAD

**Issue by erbridge** [Floppy/van_dam#79]
It's a bit dizzying. It's useful sometimes, but not constantly. I'd like to be able to toggle it on or off, or only have it spin when the image is focused.

**Comment by Floppy** [comment]
I had wondered about only spinning on mouse over, or am just removing the autorotate completely and giving you actual mouse control.

**Comment by Floppy** [comment]
Pretty sure this is accessibility thing, too. Some people would probably find it really uncomfortable.

**Comment by erbridge** [comment]
There's a `prefers-reduced-motion` feature in browsers, btw.

**Comment by erbridge** [comment]
Spin on hover feels sensible to me.

**Comment by Floppy** [comment]
oo, nice, I'll look at `prefers-reduced-motion` as well. Thanks!

**Comment by Floppy** [comment]
For now I've just replaced it with orbit controls, autorotation is easy to add back in later if we want to.
