### ISSUE TITLE
tag editing oddness

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#792]
The tag editor only lists the tags that already existed for that specific item for auto-completion.   It should list all of the tags available to make auto-complete more useful.

Also, tags in the editing box should have an "x" to remove them.  Right now you have to click in to edit, then arrow back to the one and hit backspace/delete... it's cumbersome.

Also, the editing box tags aren't sorted.

Also, if you delete a tag or tags, they are now showing in the auto-completer, and if you accidentally hit return, it will add the first tag back in.  Auto-complete shouldn't add a tag on enter unless at least one character has been typed.

These seem to be the case in all places where the tag editor exists.

**Comment by Floppy** [comment]
Just came across https://selectize.dev/plugins/2020/01/01/remove-button-copy/ which will give us the remove button.

**Comment by Floppy** [comment]
Adding all tags in the selectize `options` should give us the full list in the dropdown

**Comment by Floppy** [comment]
`addPrecedence` might solve the "hit enter without choosing anything" problem

**Comment by Floppy** [comment]
Docs are at https://selectize.dev/docs.html#configuration

**Comment by Floppy** [comment]
@ksuquix I think I've dealt with these issues, though I'm not quite sure about exactly replicating the "delete tags and hit enter" error in the same way you have. Can you try what you were doing with the latest version, and see if it behaves better for you?

**Comment by ksuquix** [comment]
It is technically still there, but with the other changes, it doesn't feel like a problem.  I think the other issues were compounding to make it an issue.   As it is, I believe this issue is closed.

**Comment by Floppy** [comment]
Thanks!
