### ISSUE TITLE
Scanner choosing preview

### ISSUE THREAD

**Issue by ksuquix** [Floppy/van_dam#795]
I think the preview is chosen by the scanner alphabetically.  
Suppose there are 20 .stl files and 2 image files.   The preview should prioritize the image files before the stl files for preview.

In addition to the image usually being the render, it greatly improves performance when you scan a bunch of new models.

**Comment by Floppy** [comment]
good idea :+1:

**Comment by ksuquix** [comment]
Not sure if it's a separate issue or not.. but images should be first displaying files in a model.

**Comment by ksuquix** [comment]
(adding because you might be able to fix both things at once with a simple sort priority)
