### ISSUE TITLE
3D preview color scheme

### ISSUE THREAD

**Issue by fl0e** [Floppy/van_dam#872]
This is probably a totally subjective issue to me and maybe noone else agrees, but I thought I mention it as a suggestion or at least something to think about or discuss.
The cyan/magenta theme in 3D previews to me feels unpleasant to look at. The single color + lighting look of i.e. thingiverse feels cleaner to me.

I edited it for me and am happy with the result with a black/greyish look, maybe there is even a way to make it configurable in some way with different hardcoded profiles.

To achieve something similar to thingiverse with van_dam I edited [preview.ts](https://github.com/Floppy/van_dam/blob/main/app/javascript/src/preview.ts) to change the material (and add an ambilight, otherwise it is too dark) 
https://github.com/Floppy/van_dam/blob/b39bf20eff20afab1d17265a22bf032aca2dc044/app/javascript/src/preview.ts#L109-L111
```diff
- const material = new THREE.MeshNormalMaterial({
-   flatShading: true
-  })
+ const material = new THREE.MeshStandardMaterial({
+   flatShading: true,
+   color: 0xcccccc
+ })
+ // add ambilight
+ this.ambiLight=new THREE.HemisphereLight( 0xffffff, .1 );
+ this.scene.add(this.ambiLight);
```
and remove cyan/magenta for the grid
https://github.com/Floppy/van_dam/blob/b39bf20eff20afab1d17265a22bf032aca2dc044/app/javascript/src/preview.ts#L165-L170
```diff
 this.gridHelper = new THREE.GridHelper( 
   this.gridSizeX, 
-   this.gridSizeX / 10,
+   this.gridSizeX / 10
-   'magenta', 
-   'cyan' 
 ) 
```

The difference can be seen in the following screenshots of a benchy in van_dam
Original:
![benchy_detail_cyan](https://user-images.githubusercontent.com/42289183/207357520-5646ef5a-2908-4131-b4eb-a30c371bf7e1.png)

Edited:
![benchy_detail_grey](https://user-images.githubusercontent.com/42289183/207357542-59fa5284-97d1-48b6-8ca2-e0eb830fc251.png)

**Comment by Floppy** [comment]
This is totally doable! The colour purely comes from the fact that I used [MeshNormalMaterial](https://threejs.org/docs/#api/en/materials/MeshNormalMaterial) in three.js as a quick way of testing things without lighting, and it sort of stuck! Great idea to have some other options 👍🏻

**Comment by Floppy** [comment]
This makes me think a less stark background might be a good thing as well. I'll have a play around.

**Comment by Floppy** [comment]
I got a bit carried away and have been working on this. If the pan/zoom are useful to you then I can easily make them configurable too. Nice one.

**Comment by Floppy** [comment]
This is looking pretty great. Now there are enough options that you can have the classic synthwave look:

<img width="983" alt="Screenshot 2022-12-14 at 23 01 58" src="https://user-images.githubusercontent.com/3565/207734055-e418fe37-e67a-471a-be7e-7c2509668e0e.png">

Or something much cleaner:

<img width="993" alt="Screenshot 2022-12-14 at 23 01 18" src="https://user-images.githubusercontent.com/3565/207734090-679649c8-8134-4005-b53c-0eb9e2965d6f.png">

**Comment by Floppy** [comment]
The only thing I've not done is make the colour of the grid editable, mainly because I'm going to rewrite the grid completely as part of #834.

**Comment by fl0e** [comment]
Just pulled the new version. Looks great, thanks again.
