### ISSUE TITLE
Feature: Apply Bulk Edit action to all models in a directory

### ISSUE THREAD

**Issue by Jafner** [Floppy/van_dam#885]
I've tried to organize my library as simply and rationally as possible. It is laid out as follows:  `/Creator 1/Group/Model/`
Where "Group" is different based how on the creator releases their content. For Patreon-first creators it's usually Month or something like "Welcome Box". For a Kickstarter creator, it would be a Project. Or for a MyMiniFactory (or other marketplace) creator, it would be organized by listing.  

All this to say, I encode organizational information into the directory structure. I hope this is a common thing to do, even if not using the specific structure I use. It would be really nice to be able to take this information and use it to apply tags or other metadata to my models.  

Right now, I'm not sure how to tell VanDAM that everything below my `/mz4250/` directory should go under the MZ4250 Creator. I could go into Bulk Edit and check the boxes for each model, but that would be several hundred clicks. Not very fun.

**Comment by Jafner** [comment]
I have been using v0.39, so if this is possible in the latest version feel free to close the issue.

**Comment by Floppy** [comment]
Interesting, good idea. I want to make the "organise" paths configurable based on model data, so vandam could put your models INTO that format, but being able to extract that information FROM the paths would be great too. I'll have a think!

**Comment by Jafner** [comment]
❤️

**Comment by ksuquix** [comment]
This would make things much less tedious for me as well...   /creator/collection/models is my normal methodology.

**Comment by mmontminy** [comment]
I'm looking forward to configurable organization. I did a quick'n'dirty hack to replace the tags with creator for organize and it's been a HUGE help in getting my library under control. I never found the tags helpful for organizing.

**Comment by Floppy** [comment]
path configuration is now released, in v0.42.0! See what you think!
