### ISSUE TITLE
Option to not auto-load in renderer

### ISSUE THREAD

**Issue by mmontminy** [Floppy/van_dam#909]
Complex models can take a long time to load and throw a browser page not responding popup. While waiting the browser tab is unresponsive, which makes edits time consuming.
I'd prefer an option to manually load the renderer when desired.

**Comment by Floppy** [comment]
Good call, makes sense. It can be very heavy.

**Comment by ksuquix** [comment]
Perhaps as part of the file processing, generate a static image to show with stl-thumb or somesuch, so initial loads have something to look with, then possibly render the stl on hover.

**Comment by mmontminy** [comment]
Part of the problem is, as soon as the browser starts to render a large/complex model, it freezes. It's part of why I never used earlier releases, it was unusable. So even if you're showing another image, the browser is still going to be unresponsive while it processes the model, preventing you from editing or clicking other navigation links etc until it's done.

I mitigate this now by setting an image as the thumbnail, so at least the index pages aren't trying to render models. I've also decimated most of the complex models so the details page loads ok. Even then you still need to wait for the render to complete before you can edit etc.

I think it's the same reason some sites (ie ;Printables) shows you a static image and requires you to click a button to load the interactive view.

It's possible my use-case is a bit different... I'm using VanDam as an on-prem ThingiVerse/Printables solution for others in my household. Nobody's interested in seeing the hundreds of parts that make up a model. It's more a matter of finding the things we've bought and getting a sense of what the finished print as a whole would look like. As such I tend to assemble the parts and save a 3mf so you can use the preview to get a sense of the finished project. The original parts are all saved as a zip/rar etc in the folder. Hence decimating the 3mf to render well isn't a concern.

**Comment by Floppy** [comment]
@ksuquix I've thought about that before - unfortunately I never worked out a good way of doing it given the client/server setup the app has at the moment. Would be great though!

@mmontminy your use case is the same as mine; these days it automatically uses images as the previews if they're available, but a more optimal preview for the 3d file would be good too.
