### ISSUE TITLE
Enhancement - Notes or Description for model.

### ISSUE THREAD

**Issue by Netrecov** [Floppy/van_dam#945]
Can i ask to add the ability to add a small (say 500 char) description or notes per model?
When managing my library of models, i also have note files that i have had to manually keep, regarding print results, and future modifications for a better print result.

**Comment by Netrecov** [comment]
i believe it could be an additional column (varchar(500) on van_dam.models, and then have an entry on the page that read from that field, and a button to update the text in that field, similar to the one for printed, pre-supported, y axis up?.

**Comment by Floppy** [comment]
Good idea! Such a good one, it's already on the todo list, in #675 😄 👍🏻
