### ISSUE TITLE
Remove "delete" action

### ISSUE THREAD

**Issue by mmontminy** [Floppy/van_dam#987]
Now that there are admin specific pages, it would be nice to remove the big red DELETE action button.
This is just asking for someone to click it not realizing what it will do, even though there's a popup.
At least the admin page requires more intent to navigate there and delete the library.

I suspect this will all clean up once multi-user support is in place, but until then this adds a little more protection against mistaken library deletion and should be an easy change.

**Comment by Floppy** [comment]
We were discussing removing that in a recent PR, I agree it's not necessary any more. :+1:

**Comment by Floppy** [comment]
done in #963
